### ISSUE TITLE
Error while trying to build jar package

### ISSUE THREAD

**Issue by mkempken** [Graylog2/graylog2-plugin-output-riemann#1] opened 2015-02-11 13:25 UTC
root@hosting-mon01:~/graylog2-plugin-output-riemann-master# java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

root@hosting-mon01:~/graylog2-plugin-output-riemann-master# mvn package
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building graylog2-plugin-output-riemann 1.0.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://clojars.org/repo/com/aphyr/riemann-java-client/0.3.1/riemann-java-client-0.3.1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.128s
[INFO] Finished at: Wed Feb 11 14:23:35 CET 2015
[INFO] Final Memory: 13M/216M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project graylog2-plugin-output-riemann: Could not resolve dependencies for project org.graylog2:graylog2-plugin-output-riemann:jar:1.0.2-SNAPSHOT: Failed to collect dependencies for [org.graylog2:graylog2-plugin:jar:1.0.0-beta.3 (provided), com.aphyr:riemann-java-client:jar:0.3.1 (compile)]: Failed to read artifact descriptor for com.aphyr:riemann-java-client:jar:0.3.1: Could not transfer artifact com.aphyr:riemann-java-client:pom:0.3.1 from/to clojars.org (http://clojars.org/repo): Access denied to: http://clojars.org/repo/com/aphyr/riemann-java-client/0.3.1/riemann-java-client-0.3.1.pom , ReasonPhrase:Forbidden. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
root@hosting-mon01:~/graylog2-plugin-output-riemann-master# 

What am i doing wrong? Any suggestions? Thanks in advance (Ubuntu 14.04.1 LTS).

**Comment by joschi** [comment] 2015-02-11 14:31
Looks like [Clojars](https://clojars.org/) either had a temporary problem with delivering artifacts or there's a problem accessing clojars.org from your system.

Either way, I can't reproduce the problem and it's not really a bug in this plugin, so I'm closing this issue.

**Closed as completed by joschi** 2015-02-11 14:31 UTC

**Comment by mkempken** [comment] 2015-02-12 09:02
Recomplied it on a different machine, seems like a proxy issue. Worked for me. Thanks
